### ISSUE TITLE
Error on send using comthreads

### ISSUE THREAD

**Issue by daylanKifky** [Xinne/osc4py3#4]
The following snippet:

```python
from osc4py3.as_eventloop import *
from osc4py3 import oscbuildparse
osc_startup()
# Make client channels to send packets.
osc_udp_client("127.0.0.1", 7000, "local")
# Build a simple message and send it.
msg = oscbuildparse.OSCMessage("/test/me", ",sif", ["text", 672, 8.871])
osc_send(msg, "local")
osc_process()
osc_terminate()
```
works fine, but when I change to comthreads 
```python 
from osc4py3.as_comthreads  import *
```
an error is raised, and the message is not sent

The trace I got ends with
```
Python3_osc4py3/osc4py3/osctoolspools.py", line 153, in send_job
    raise RuntimeError("WorkQueue jobs terminated.")
```
[(full log here)](https://github.com/Xinne/osc4py3/files/2225757/send_comthreads.log)

I'm running python 3.6.5 on Linux 4.15.0-29-generic x86_64

Anyone has an idea of what's happening?

**Comment by daylanKifky** [comment]
Update:
This error was happening on the [pypi package, version 1.0.4](https://pypi.org/project/osc4py3/).
The version on this repository is working fine to me, even if it's labelled 1.0.1

Would be great if the changes on this repository get merged with the official one

**Comment by vivi90** [comment]
## Workaround
With version `1.0.1` and `1.0.3` it works perfectly fine. 
It's broken since `1.0.4` like mentioned in https://github.com/Xinne/osc4py3/issues/4#issuecomment-409595319.
```
$ pip install osc4py3==1.0.3
````

**Comment by vivi90** [comment]
Please fix this issue, if possible 🙂
