### ISSUE TITLE
How can I receive values in 1 second

### ISSUE THREAD

**Issue by ambuje** [Xinne/osc4py3#6]
I am receiving 20 values in 1 second, How can I receive 1 value in 1 sec? Maybe how can I stop the server for the time being and take values whenever I want

**Comment by lpointal** [comment]
How do you proceed?

**Comment by lpointal** [comment]
If the system which send the values generate 20 values/second via OSC, then you will receive them (unless some packet were dropped by network).
You can add a test-case in your handler function and only consider value at a fixed period (dimiss others), or eventually build an average of last N values.

**Comment by ambuje** [comment]
from osc4py3.as_eventloop import *
from osc4py3 import oscmethod as osm

def eeg_handler(ch1, ch2, ch3, ch4,ch5):
    
    print(ch1)
    


osc_startup()


osc_udp_server("192.168.43.197", 5006, "aservername")


osc_method("/muse/eeg", eeg_handler)



osc_process()

osc_terminate()


This is my code can you guide me how can I do what you told ?

**Comment by ambuje** [comment]
My problem statement - I have an EEG device "muse" I want to take values from it 1 value per second.  The device has OSC streaming

**Comment by lpointal** [comment]
From my knowledge of OSC, once you registered to receive messages from a source, yo receive all messages. Personally I would insert a test at beginning of handler function to dismiss unwanted values, based on the time or simply on a global counter modulo 20.

**Comment by lpointal** [comment]
evtcount
def eeg_handler(ch1, ch2, ch3, ch4,ch5):
    global evtcount
    evtcount += 1
    if evtcount % 20 != 0:
        return
    print(ch1)

**Comment by lpointal** [comment]
Here a solution:
```
evtcount = 0
def eeg_handler(ch1, ch2, ch3, ch4,ch5):
    global evtcount
    evtcount += 1
    if evtcount % 20 != 0:
        return
    print(ch1)
    # and other stuff here
```

**Comment by ambuje** [comment]
The 20 is a very approximate value sir I will try and revert back to you in approx 30 minutes

**Comment by ambuje** [comment]
Thanks  mate 👍
